# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0.0
maven_group=net.xiaoyu233
archives_name=SuperFirework
enabled_platforms=fabric,forge
# Minecraft properties
minecraft_version=1.20.1
# Dependencies
architectury_api_version=9.2.14
fabric_loader_version=0.16.10
fabric_api_version=0.92.3+1.20.1
forge_version=1.20.1-47.3.27
