# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=1.0.2+1.21.1
maven_group=net.xiaoyu233
archives_name=SuperFirework
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
yarn_mappings = 1.21.1+build.3
# Dependencies
architectury_api_version = 13.0.8
fabric_loader_version = 0.18.4
fabric_api_version = 0.116.7+1.21.1
neoforge_version = 21.1.215
yarn_mappings_patch_neoforge_version = 1.21+build.6