modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "superfirework"
version = "${version}"
displayName = "SuperFirework"
authors = "XiaoYu233"
description = '''

'''
#logoFile = ""

[[dependencies.superfirework]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.superfirework]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.superfirework]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "superfirework.mixins.json"
